### PR TITLE
Fixed misleading argument name

### PR DESCRIPTION
**Pull request by dellaert**
from axis_angle to quaternion

### CODE REVIEW

**Comment by sandwichmaker** [comment]
@dellaert thanks for the patch, but we only accept changes on gerrit. Please follow http://ceres-solver.org/contributing.html.

**Comment by dellaert** [comment]
Yeah, sorry, that's too involved for me :-/

**Comment by alexsmac** [comment]
Thanks @dellaert I've raised this as a CL [here](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17600)

**Comment by alexsmac** [comment]
Closing as this fix is now in master

**Pull request closed without merging**
