### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by LilyWangL**
Ceres is available as a port in vcpkg, a C++ library manager that simplifies installation for ceres and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build ceres, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by sandwichmaker** [comment]
@LilyWangL thanks for this. There is another patch on gerrit 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15820

could you look into merging these two and posting this patch on ceres-solver-review.googlesource.com

using the instructions at 

http://ceres-solver.org/contributing.html

**Comment by LilyWangL** [comment]
> @LilyWangL thanks for this. There is another patch on gerrit
> 
> https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15820
> 
> could you look into merging these two and posting this patch on ceres-solver-review.googlesource.com
> 
> using the instructions at
> 
> http://ceres-solver.org/contributing.html

@sandwichmaker Ok, I will fix it soon.

**Comment by sandwichmaker** [comment]
Fantastic! thank you.

**Comment by LilyWangL** [comment]
@sandwichmaker Thanks for your reply. I have fixed my commit and sent an email to Griffin, he will continue to fix his commit: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15820.

**Comment by sandwichmaker** [comment]
Thank you, Closing this as obsolete.

**Pull request closed without merging**
