### PR TITLE
Show SuiteSparse directory hints CMake variables when SuiteSparse is not found

### PR DESCRIPTION
**Pull request by aschier**

### CODE REVIEW

**Comment by aschier** [comment]
I had the problem, that ceres does not expose the variables ``SUITESPARSE_INCLUDE_DIR_HINTS`` and ``SUITESPARSE_LIBRARY_DIR_HINTS``, but low-level variables like ``CAMD_INCLUDE_DIR`` and ``CAMD_LIBRARY``. Setting these variables for the 5 needed SuiteSparse libaries is not only more work, but leads to linking problems in some cases, when using the HINTS variables autodetects everything correctly, see https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/87.

You may want to have a look at the bug, if you can help what possibly goes wrong when SuiteSparse/Ceres include wrong symbols in their object files.

This patch proposes to expose these variables when finding SuiteSparse failed. Another option would be to always expose them.
In my projects I need to add the hidden BLAS and LAPACK variables as well, so I included them there, too.

**Comment by aschier** [comment]
Is there a reason why ceres is not using SuiteSparse exported targets or is it just not implemented, yet?

**Comment by alexsmac** [comment]
@aschier this is not a bug.  The documentation for Ceres already covers at length how to configure external dependencies [here](http://ceres-solver.org/installation.html#options-controlling-ceres-dependency-locations), and that documentation is also replicated in FindSuiteSparse.cmake [here](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/FindSuiteSparse.cmake#L32).

Variables such as `CAMD_INCLUDE_DIR` are private variables marked as advanced that are the result of calls to `find_path/library()` and are thus cache variables.  If you reset them yourself externally you will implicitly disable the corresponding evaluation of the `find_path/library()` function as a cached variable with the specified output name already exists.  This may break assumptions about the validity of the results in the script and so the result is undefined behaviour.  You should instead use the approach detailed in the documentation to configure Ceres.

We do not use exported targets generated by suitesparse-metis-for-windows as it is not an official release, and is not used by major distributions to build their packages of SuiteSparse.  We are open to adding optional support for it, as we already do for other dependencies such as glog and gflags in our FindXXX.cmake scripts for them.  If you would like to contribute to that, please [this section](http://ceres-solver.org/contributing.html) of the docs as we do not accept PRs via GitHub.

**Comment by aschier** [comment]
Fair point, it is documented.

But the documentation section

> These variables are available to set in the CMake GUI. They are visible in the Standard View if the library has not been found (but the current Ceres configuration requires it), but are always visible in the Advanced View. 

seems not to be true for the SuiteSparse variables ``SUITESPARSE_INCLUDE_DIR_HINTS`` and ``SUITESPARSE_LIBRARY_DIR_HINTS``. You need to add them manually (and then it works like a charm).

It currently _works for me_, so I will not invest too much time in it now, but I thought you may appreciate the feedback on this little pitfall.
I came across the problem when documenting how to create a build environment for a rather complex project and it was not obvious which option is missing, when configuring ceres. Your point about the documentation is of course correct, so I currently just keep it as works for me now.

**Pull request closed without merging**
