### PR TITLE
Update FindGlog.cmake to create glog::glog target

### LINKED ISSUE #845: findGlog does not always define glog::glog
When using a `CONFIG`, Glog defines the `glog::glog` target, which is recommended to use. However, when searching for the files "by hand", this target is not defined.

### PR DESCRIPTION
**Pull request by KrisThielemans**
Fixes #845

### CODE REVIEW

**Comment by sandwichmaker** [comment]
Thanks @KrisThielemans but we do not (currently) accept pull requests on github. Could you follow the instructions at 
http://ceres-solver.org/contributing.html and submit it for review.

**Comment by KrisThielemans** [comment]
Apologies, but this is too much effort for a 3 line change for me. I just have too much to do.

Feel free to copy/rework these lines and merge it yourself.

**Comment by sandwichmaker** [comment]
Thats fair, I will upstream the change and credit you.

**Comment by sandwichmaker** [comment]
This has been merged via gerrit.

**Pull request closed without merging**
