### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sandwichmaker** [comment]
Thanks for the pull request, but we do not (yet) accept patches on github. Please see the instructions at

http://ceres-solver.org/contributing.html

for how to submit patches to ceres.

**Comment by sloriot** [comment]
You should commit it directly yourself.

**Comment by sandwichmaker** [comment]
will do!

**Comment by sandwichmaker** [comment]
also I am working on changing the way ceres solver is developed and move
the development to github, so that commits yours can be accepted. The
current system is too cumbersome.

**Comment by sloriot** [comment]
With also struggled in the past with our old infrastructure but now that we are fully on github it is easier for us to accept external contribution. Good luck!

**Pull request closed without merging**
